const Footer = () => {
  return (
    <div className="pt-8 mt-8 border-t border-solid border-mindfire-footer-border-color">
      <span className="text-mindfire-footer-text-color text-base">
        This page was generated by{" "}
        <a
          className="text-mindfire-text-red font-semibold text-lg hover-underline"
          href="https://pages.github.com"
        >
          GitHub Pages
        </a>
        .
      </span>
    </div>
  );
};

export default Footer;
